FROM maven:3-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .

COPY src ./src
RUN mvn clean package -DskipTests

FROM  eclipse-temurin-21-alpine

WORKDIR /app

COPY --from=build /app/target/merchandiseMgmtERP-0.0.1-SNAPSHOT.jar merchandiseMgmtERP.jar

EXPOSE 8089
ENTRYPOINT ["java","-jar","merchandiseMgmtERP.jar"]